ALTER TABLE stocks ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS long_name VARCHAR(255);
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS sector VARCHAR(255);
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);